# Book keeping parameters

output_path: /Users/thomasedwards/Dropbox/Work/Gravitational_Waves/JaxGW/plots

# Noise parameters

seed: 1234
f_sampling: 2048
duration: 16
fmin: 20
ifos:
  - H1
  - L1

# Injection parameters

m1: 36
m2: 29.
chi1: 0.1
chi2: 0.1
dist_mpc: 500
tc: 0.02
phic: 0.1
inclination: 0.5
polarization_angle: 0.2
ra: 1.2
dec: 0.3